"use strict";

import { QueryInterface, DataTypes } from "sequelize";

module.exports = {
  async up(queryInterface: QueryInterface, Sequelize: typeof DataTypes) {
    await queryInterface.bulkInsert("Countries", [
      {
        name: "Afghanistan",
        code: "AF",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Albania",
        code: "AL",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Algeria",
        code: "DZ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Andorra",
        code: "AD",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Angola",
        code: "AO",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Antigua and Barbuda",
        code: "AG",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Argentina",
        code: "AR",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Armenia",
        code: "AM",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Australia",
        code: "AU",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Austria",
        code: "AT",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Azerbaijan",
        code: "AZ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Bahamas",
        code: "BS",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Bahrain",
        code: "BH",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Bangladesh",
        code: "BD",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Barbados",
        code: "BB",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Belarus",
        code: "BY",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Belgium",
        code: "BE",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Belize",
        code: "BZ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Benin",
        code: "BJ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Bhutan",
        code: "BT",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Bolivia",
        code: "BO",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Bosnia and Herzegovina",
        code: "BA",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Botswana",
        code: "BW",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Brazil",
        code: "BR",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Brunei",
        code: "BN",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Bulgaria",
        code: "BG",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Burkina Faso",
        code: "BF",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Burundi",
        code: "BI",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Cabo Verde",
        code: "CV",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Cambodia",
        code: "KH",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Cameroon",
        code: "CM",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Canada",
        code: "CA",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Central African Republic",
        code: "CF",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Chad",
        code: "TD",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Chile",
        code: "CL",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "China",
        code: "CN",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Colombia",
        code: "CO",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Comoros",
        code: "KM",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Congo (Congo-Brazzaville)",
        code: "CG",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Costa Rica",
        code: "CR",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Croatia",
        code: "HR",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Cuba",
        code: "CU",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Cyprus",
        code: "CY",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Czechia (Czech Republic)",
        code: "CZ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Democratic Republic of the Congo",
        code: "CD",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Denmark",
        code: "DK",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Djibouti",
        code: "DJ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Dominica",
        code: "DM",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Dominican Republic",
        code: "DO",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Ecuador",
        code: "EC",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Egypt",
        code: "EG",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "El Salvador",
        code: "SV",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Equatorial Guinea",
        code: "GQ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Eritrea",
        code: "ER",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Estonia",
        code: "EE",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Eswatini",
        code: "SZ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Ethiopia",
        code: "ET",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Fiji",
        code: "FJ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Finland",
        code: "FI",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "France",
        code: "FR",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Gabon",
        code: "GA",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Gambia",
        code: "GM",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Georgia",
        code: "GE",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Germany",
        code: "DE",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Ghana",
        code: "GH",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Greece",
        code: "GR",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Grenada",
        code: "GD",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Guatemala",
        code: "GT",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Guinea",
        code: "GN",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Guinea-Bissau",
        code: "GW",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Guyana",
        code: "GY",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Haiti",
        code: "HT",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Honduras",
        code: "HN",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Hungary",
        code: "HU",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Iceland",
        code: "IS",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "India",
        code: "IN",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Indonesia",
        code: "ID",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Iran",
        code: "IR",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Iraq",
        code: "IQ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Ireland",
        code: "IE",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Israel",
        code: "IL",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Italy",
        code: "IT",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Jamaica",
        code: "JM",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Japan",
        code: "JP",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Jordan",
        code: "JO",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Kazakhstan",
        code: "KZ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Kenya",
        code: "KE",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Kiribati",
        code: "KI",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Kuwait",
        code: "KW",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Kyrgyzstan",
        code: "KG",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Laos",
        code: "LA",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Latvia",
        code: "LV",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Lebanon",
        code: "LB",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Lesotho",
        code: "LS",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Liberia",
        code: "LR",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Libya",
        code: "LY",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Liechtenstein",
        code: "LI",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Lithuania",
        code: "LT",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Luxembourg",
        code: "LU",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Madagascar",
        code: "MG",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Malawi",
        code: "MW",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Malaysia",
        code: "MY",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Maldives",
        code: "MV",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Mali",
        code: "ML",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Malta",
        code: "MT",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Marshall Islands",
        code: "MH",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Mauritania",
        code: "MR",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Mauritius",
        code: "MU",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Mexico",
        code: "MX",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Micronesia",
        code: "FM",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Moldova",
        code: "MD",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Monaco",
        code: "MC",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Mongolia",
        code: "MN",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Montenegro",
        code: "ME",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Morocco",
        code: "MA",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Mozambique",
        code: "MZ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Myanmar (formerly Burma)",
        code: "MM",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Namibia",
        code: "NA",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Nauru",
        code: "NR",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Nepal",
        code: "NP",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Netherlands",
        code: "NL",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "New Zealand",
        code: "NZ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Nicaragua",
        code: "NI",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Niger",
        code: "NE",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Nigeria",
        code: "NG",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "North Korea",
        code: "KP",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "North Macedonia",
        code: "MK",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Norway",
        code: "NO",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Oman",
        code: "OM",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Pakistan",
        code: "PK",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Palau",
        code: "PW",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Palestine State",
        code: "PS",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Panama",
        code: "PA",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Papua New Guinea",
        code: "PG",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Paraguay",
        code: "PY",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Peru",
        code: "PE",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Philippines",
        code: "PH",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Poland",
        code: "PL",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Portugal",
        code: "PT",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Qatar",
        code: "QA",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Romania",
        code: "RO",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Russia",
        code: "RU",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Rwanda",
        code: "RW",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Saint Kitts and Nevis",
        code: "KN",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Saint Lucia",
        code: "LC",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Saint Vincent and the Grenadines",
        code: "VC",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Samoa",
        code: "WS",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "San Marino",
        code: "SM",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Sao Tome and Principe",
        code: "ST",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Saudi Arabia",
        code: "SA",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Senegal",
        code: "SN",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Serbia",
        code: "RS",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Seychelles",
        code: "SC",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Sierra Leone",
        code: "SL",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Singapore",
        code: "SG",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Slovakia",
        code: "SK",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Slovenia",
        code: "SI",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Solomon Islands",
        code: "SB",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Somalia",
        code: "SO",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "South Africa",
        code: "ZA",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "South Korea",
        code: "KR",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "South Sudan",
        code: "SS",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Spain",
        code: "ES",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Sri Lanka",
        code: "LK",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Sudan",
        code: "SD",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Suriname",
        code: "SR",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Sweden",
        code: "SE",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Switzerland",
        code: "CH",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Syria",
        code: "SY",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Taiwan",
        code: "TW",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Tajikistan",
        code: "TJ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Tanzania",
        code: "TZ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Thailand",
        code: "TH",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Timor-Leste",
        code: "TL",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Togo",
        code: "TG",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Tonga",
        code: "TO",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Trinidad and Tobago",
        code: "TT",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Tunisia",
        code: "TN",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Turkey",
        code: "TR",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Turkmenistan",
        code: "TM",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Tuvalu",
        code: "TV",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Uganda",
        code: "UG",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Ukraine",
        code: "UA",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "United Arab Emirates",
        code: "AE",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "United Kingdom",
        code: "GB",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "United States of America",
        code: "US",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Uruguay",
        code: "UY",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Uzbekistan",
        code: "UZ",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Vanuatu",
        code: "VU",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Venezuela",
        code: "VE",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Vietnam",
        code: "VN",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Yemen",
        code: "YE",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Zambia",
        code: "ZM",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: "Zimbabwe",
        code: "ZW",
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  async down(queryInterface: QueryInterface, Sequelize: typeof DataTypes) {
    await queryInterface.bulkDelete("Countries", null, {});
  },
};
